apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
data:
  slackBotToken: <REPLACE WITH TOKEen.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slackbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slackbot
        version: prod
      annotations:
        prometheus.io/path: '/prometheus'
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: slackbot
        image: gcr.io/<PROJECT_ID>/slackbot:latest
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "sleep 30 && /usr/bin/java -jar /opt/spring-cloud/lib/spring-boot-slackbot-example-0.0.1-SNAPSHOT.jar" ]

        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: slackBotToken
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: slackBotToken

---
apiVersion: v1
kind: Service
metadata:
  name: slackbot
  labels:
    app: slackbot
spec:
  selector:
    app: slackbot
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: slack.com
spec:
  hosts:
  - slack.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: slackbot
          servicePort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: slackbot
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: slackbot
        port:
          number: 8080